# Generated by Django 4.1.6 on 2023-02-10 02:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name1', models.CharField(max_length=50, verbose_name='メニュー名')),
                ('size1', models.CharField(max_length=3, verbose_name='サイズ')),
                ('price1', models.IntegerField(verbose_name='値段')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真')),
                ('about1', models.TextField(max_length=300, verbose_name='紹介文')),
                ('menu_name2', models.CharField(max_length=50, verbose_name='メニュー名')),
                ('size2', models.CharField(max_length=3, verbose_name='サイズ')),
                ('price2', models.IntegerField(verbose_name='値段')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真')),
                ('about2', models.TextField(max_length=300, verbose_name='紹介文')),
                ('menu_name3', models.CharField(max_length=50, verbose_name='メニュー名')),
                ('size3', models.CharField(max_length=3, verbose_name='サイズ')),
                ('price3', models.IntegerField(verbose_name='値段')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真')),
                ('about3', models.TextField(max_length=300, verbose_name='紹介文')),
                ('menu_name4', models.CharField(max_length=50, verbose_name='メニュー名')),
                ('size4', models.CharField(max_length=3, verbose_name='サイズ')),
                ('price4', models.IntegerField(verbose_name='値段')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真')),
                ('about4', models.TextField(max_length=300, verbose_name='紹介文')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False, verbose_name='storeid')),
                ('store_name', models.CharField(max_length=30, verbose_name='店舗名')),
                ('postal_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('adress1', models.CharField(choices=[('北海道', '北海道'), ('青森', '青森'), ('岩手', '岩手'), ('宮城', '宮城'), ('秋田', '秋田'), ('山形', '山形'), ('福島', '福島'), ('茨城', '茨城'), ('栃木', '栃木'), ('群馬', '群馬'), ('埼玉', '埼玉'), ('千葉', '千葉'), ('東京', '東京'), ('神奈川', '神奈川'), ('新潟', '新潟'), ('富山', '富山'), ('石川', '石川'), ('福井', '福井'), ('山梨', '山梨'), ('長野', '長野'), ('岐阜', '岐阜'), ('静岡', '静岡'), ('愛知', '愛知'), ('三重', '三重'), ('滋賀', '滋賀'), ('京都', '京都'), ('大阪', '大阪'), ('兵庫', '兵庫'), ('奈良', '奈良'), ('和歌山', '和歌山'), ('鳥取', '鳥取'), ('島根', '島根'), ('岡山', '岡山'), ('広島', '広島'), ('山口', '山口'), ('徳島', '徳島'), ('香川', '香川'), ('愛媛', '愛媛'), ('高知', '高知'), ('福岡', '福岡'), ('佐賀', '佐賀'), ('長崎', '長崎'), ('熊本', '熊本'), ('大分', '大分'), ('宮城', '宮城'), ('鹿児島', '鹿児島'), ('沖縄', '沖縄')], max_length=20, verbose_name='住所(xx県)')),
                ('adress2', models.CharField(max_length=20, verbose_name='住所(xx市)')),
                ('adress3', models.CharField(max_length=20, verbose_name='住所(xx丁目xx番地)')),
                ('adress4', models.CharField(max_length=20, verbose_name='住所(ビル名など)')),
                ('phone_number', models.CharField(max_length=13, verbose_name='電話番号')),
                ('seat', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='席数')),
                ('bussiness_hours_start', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default='選択してください', max_length=3, verbose_name='営業開始')),
                ('bussiness_hours_end', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default='選択してください', max_length=3, verbose_name='営業終了')),
                ('holiday1', models.CharField(choices=[('月曜日', '月曜日'), ('火曜日', '火曜日'), ('水曜日', '水曜日'), ('木曜日', '木曜日'), ('金曜日', '金曜日'), ('土曜日', '土曜日'), ('日曜日', '日曜日'), ('祝日', '祝日'), ('なし', 'なし')], default='祝日', max_length=4, verbose_name='定休日1')),
                ('holiday2', models.CharField(choices=[('月曜日', '月曜日'), ('火曜日', '火曜日'), ('水曜日', '水曜日'), ('木曜日', '木曜日'), ('金曜日', '金曜日'), ('土曜日', '土曜日'), ('日曜日', '日曜日'), ('祝日', '祝日'), ('なし', 'なし')], default='なし', max_length=4, verbose_name='定休日2')),
                ('holiday3', models.CharField(choices=[('月曜日', '月曜日'), ('火曜日', '火曜日'), ('水曜日', '水曜日'), ('木曜日', '木曜日'), ('金曜日', '金曜日'), ('土曜日', '土曜日'), ('日曜日', '日曜日'), ('祝日', '祝日'), ('なし', 'なし')], default='なし', max_length=4, verbose_name='定休日3')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真3')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真4')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真5')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真6')),
                ('photo7', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真7')),
                ('photo8', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真8')),
                ('photo9', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真9')),
                ('photo10', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真10')),
                ('about', models.TextField(max_length=300, verbose_name='紹介文')),
                ('bp_id', models.ForeignKey(max_length=16, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='事業者ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='予約者名')),
                ('reservation_mail', models.EmailField(blank=True, max_length=40, null=True, verbose_name='予約者メールアドレス')),
                ('reservation_day', models.CharField(max_length=20, verbose_name='予約希望日')),
                ('reservation_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='予約者電話番号')),
                ('reservation_hour', models.IntegerField(max_length=3, verbose_name='予約時間')),
                ('nop', models.IntegerField(verbose_name='予約人数')),
                ('menu1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_1', to='comp.menu', verbose_name='メニュー1')),
                ('menu2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_2', to='comp.menu', verbose_name='メニュー2')),
                ('menu3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_3', to='comp.menu', verbose_name='メニュー3')),
                ('menu4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_4', to='comp.menu', verbose_name='メニュー4')),
                ('menu5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_5', to='comp.menu', verbose_name='メニュー5')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.store', verbose_name='店舗ID')),
                ('user_id', models.ForeignKey(blank=True, max_length=16, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.store', verbose_name='店舗ID'),
        ),
        migrations.CreateModel(
            name='Kuchikomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='評価点数')),
                ('impression', models.TextField(max_length=2000, verbose_name='評価内容')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.store', verbose_name='店舗ID')),
                ('user_id', models.ForeignKey(max_length=16, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
    ]
