# Generated by Django 4.1.3 on 2023-01-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='store',
            name='unique_bo',
        ),
    ]
