# Generated by Django 4.1.3 on 2023-01-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='holiday',
            field=models.CharField(choices=[('mon', '月曜日'), ('tue', '火曜日'), ('wed', '水曜日'), ('thr', '木曜日'), ('fri', '金曜日'), ('sat', '土曜日'), ('sun', '日曜日'), ('cel', '祝日')], default='cel', max_length=3),
        ),
    ]
