# Generated by Django 4.1.3 on 2023-02-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='bussiness_hours_end',
            field=models.IntegerField(choices=[('１時', 1), ('2時', 2), ('3時', 3), ('4時', 4), ('5時', 5), ('6時', 6), ('7時', 7), ('8時', 8), ('9時', 9), ('10時', 10), ('11時', 11), ('12時', 12), ('13時', 13), ('14時', 14), ('15時', 15), ('16時', 16), ('17時', 17), ('18時', 18), ('19時', 19), ('20時', 20), ('21時', 21), ('22時', 22), ('23時', 23), ('24時', 24)], default='選択してください', max_length=3, verbose_name='営業終了'),
        ),
        migrations.AlterField(
            model_name='store',
            name='bussiness_hours_start',
            field=models.IntegerField(choices=[('１時', 1), ('2時', 2), ('3時', 3), ('4時', 4), ('5時', 5), ('6時', 6), ('7時', 7), ('8時', 8), ('9時', 9), ('10時', 10), ('11時', 11), ('12時', 12), ('13時', 13), ('14時', 14), ('15時', 15), ('16時', 16), ('17時', 17), ('18時', 18), ('19時', 19), ('20時', 20), ('21時', 21), ('22時', 22), ('23時', 23), ('24時', 24)], default='選択してください', max_length=3, verbose_name='営業開始'),
        ),
    ]
