# Generated by Django 4.1.3 on 2023-01-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真1'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真2'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真3'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真4'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真5'),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo10',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真10'),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真2'),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真3'),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真4'),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真5'),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真6'),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo7',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真7'),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo8',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真8'),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo9',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真9'),
        ),
    ]
