# Generated by Django 4.1.3 on 2023-01-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_hour',
            field=models.CharField(choices=[('１時', '１時'), ('2時', '2時'), ('3時', '3時'), ('4時', '4時'), ('5時', '5時'), ('6時', '6時'), ('7時', '7時'), ('8時', '8時'), ('9時', '9時'), ('10時', '10時'), ('11時', '11時'), ('12時', '12時'), ('13時', '13時'), ('14時', '14時'), ('15時', '15時'), ('16時', '16時'), ('17時', '17時'), ('18時', '18時'), ('19時', '19時'), ('20時', '20時'), ('21時', '21時'), ('22時', '22時'), ('23時', '23時'), ('24時', '24時')], default='選択してください', max_length=3, verbose_name='予約希望時間'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_minute',
            field=models.CharField(choices=[('00分', '00分'), ('15分', '15分'), ('30分', '30分'), ('45分', '45分')], default='選択してください', max_length=3, verbose_name=''),
        ),
    ]
