# Generated by Django 4.1.3 on 2023-01-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_store_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='holiday',
        ),
        migrations.AddField(
            model_name='store',
            name='end_minute',
            field=models.CharField(choices=[(0, '00分'), (15, '15分'), (30, '30分'), (45, '45分')], default='選択してください', max_length=3, verbose_name=''),
        ),
        migrations.AddField(
            model_name='store',
            name='holiday1',
            field=models.CharField(choices=[('mon', '月曜日'), ('tue', '火曜日'), ('wed', '水曜日'), ('thr', '木曜日'), ('fri', '金曜日'), ('sat', '土曜日'), ('sun', '日曜日'), ('cel', '祝日'), ('none', '無し')], default='cel', max_length=4, verbose_name='定休日1'),
        ),
        migrations.AddField(
            model_name='store',
            name='holiday2',
            field=models.CharField(choices=[('mon', '月曜日'), ('tue', '火曜日'), ('wed', '水曜日'), ('thr', '木曜日'), ('fri', '金曜日'), ('sat', '土曜日'), ('sun', '日曜日'), ('cel', '祝日'), ('none', '無し')], default='none', max_length=4, verbose_name='定休日2'),
        ),
        migrations.AddField(
            model_name='store',
            name='holiday3',
            field=models.CharField(choices=[('mon', '月曜日'), ('tue', '火曜日'), ('wed', '水曜日'), ('thr', '木曜日'), ('fri', '金曜日'), ('sat', '土曜日'), ('sun', '日曜日'), ('cel', '祝日'), ('none', '無し')], default='none', max_length=4, verbose_name='定休日3'),
        ),
        migrations.AddField(
            model_name='store',
            name='start_minute',
            field=models.CharField(choices=[(0, '00分'), (15, '15分'), (30, '30分'), (45, '45分')], default='選択してください', max_length=3, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='bussiness_hours_end',
            field=models.CharField(choices=[(1, '１時'), (2, '2時'), (3, '3時'), (4, '4時'), (5, '5時'), (6, '6時'), (7, '7時'), (8, '8時'), (9, '9時'), (10, '10時'), (11, '11時'), (12, '12時'), (13, '13時'), (14, '14時'), (15, '15時'), (16, '16時'), (17, '17時'), (18, '18時'), (19, '19時'), (20, '20時'), (21, '21時'), (22, '22時'), (23, '23時'), (24, '24時')], default='選択してください', max_length=3, verbose_name='営業終了'),
        ),
        migrations.AlterField(
            model_name='store',
            name='bussiness_hours_start',
            field=models.CharField(choices=[(1, '１時'), (2, '2時'), (3, '3時'), (4, '4時'), (5, '5時'), (6, '6時'), (7, '7時'), (8, '8時'), (9, '9時'), (10, '10時'), (11, '11時'), (12, '12時'), (13, '13時'), (14, '14時'), (15, '15時'), (16, '16時'), (17, '17時'), (18, '18時'), (19, '19時'), (20, '20時'), (21, '21時'), (22, '22時'), (23, '23時'), (24, '24時')], default='選択してください', max_length=3, verbose_name='営業開始'),
        ),
    ]
