# Generated by Django 4.1.3 on 2023-01-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_remove_reservation_time_reservation_reservation_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='写真1'),
        ),
    ]
