# Generated by Django 4.1.3 on 2023-01-24 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0003_alter_store_photo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='予約希望日'),
        ),
    ]
