# Generated by Django 4.1.3 on 2023-02-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0003_alter_store_bussiness_hours_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_hour',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default='選択してください', max_length=3, verbose_name='予約時間'),
        ),
    ]
