# Generated by Django 4.1.3 on 2023-01-17 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0003_remove_store_holiday_store_end_minute_store_holiday1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='bussiness_hours_end',
            field=models.CharField(choices=[('１時', '１時'), ('2時', '2時'), ('3時', '3時'), ('4時', '4時'), ('5時', '5時'), ('6時', '6時'), ('7時', '7時'), ('8時', '8時'), ('9時', '9時'), ('10時', '10時'), ('11時', '11時'), ('12時', '12時'), ('13時', '13時'), ('14時', '14時'), ('15時', '15時'), ('16時', '16時'), ('17時', '17時'), ('18時', '18時'), ('19時', '19時'), ('20時', '20時'), ('21時', '21時'), ('22時', '22時'), ('23時', '23時'), ('24時', '24時')], default='選択してください', max_length=3, verbose_name='営業終了'),
        ),
        migrations.AlterField(
            model_name='store',
            name='bussiness_hours_start',
            field=models.CharField(choices=[('１時', '１時'), ('2時', '2時'), ('3時', '3時'), ('4時', '4時'), ('5時', '5時'), ('6時', '6時'), ('7時', '7時'), ('8時', '8時'), ('9時', '9時'), ('10時', '10時'), ('11時', '11時'), ('12時', '12時'), ('13時', '13時'), ('14時', '14時'), ('15時', '15時'), ('16時', '16時'), ('17時', '17時'), ('18時', '18時'), ('19時', '19時'), ('20時', '20時'), ('21時', '21時'), ('22時', '22時'), ('23時', '23時'), ('24時', '24時')], default='選択してください', max_length=3, verbose_name='営業開始'),
        ),
        migrations.AlterField(
            model_name='store',
            name='end_minute',
            field=models.CharField(choices=[('00分', '00分'), ('15分', '15分'), ('30分', '30分'), ('45分', '45分')], default='選択してください', max_length=3, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='postal_code',
            field=models.CharField(max_length=8, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='store',
            name='seat',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='席数'),
        ),
        migrations.AlterField(
            model_name='store',
            name='seat_reservationable',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='予約可能な席数'),
        ),
        migrations.AlterField(
            model_name='store',
            name='start_minute',
            field=models.CharField(choices=[('00分', '00分'), ('15分', '15分'), ('30分', '30分'), ('45分', '45分')], default='選択してください', max_length=3, verbose_name=''),
        ),
    ]
