# Generated by Django 4.1.3 on 2023-01-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0004_alter_store_bussiness_hours_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='holiday1',
            field=models.CharField(choices=[('月曜日', '月曜日'), ('火曜日', '火曜日'), ('水曜日', '水曜日'), ('木曜日', '木曜日'), ('金曜日', '金曜日'), ('土曜日', '土曜日'), ('日曜日', '日曜日'), ('祝日', '祝日'), ('', '')], default='祝日', max_length=4, verbose_name='定休日1'),
        ),
        migrations.AlterField(
            model_name='store',
            name='holiday2',
            field=models.CharField(choices=[('月曜日', '月曜日'), ('火曜日', '火曜日'), ('水曜日', '水曜日'), ('木曜日', '木曜日'), ('金曜日', '金曜日'), ('土曜日', '土曜日'), ('日曜日', '日曜日'), ('祝日', '祝日'), ('', '')], default='', max_length=4, verbose_name='定休日2'),
        ),
        migrations.AlterField(
            model_name='store',
            name='holiday3',
            field=models.CharField(choices=[('月曜日', '月曜日'), ('火曜日', '火曜日'), ('水曜日', '水曜日'), ('木曜日', '木曜日'), ('金曜日', '金曜日'), ('土曜日', '土曜日'), ('日曜日', '日曜日'), ('祝日', '祝日'), ('', '')], default='', max_length=4, verbose_name='定休日3'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('bp_id',), name='unique_bo'),
        ),
    ]
