# Generated by Django 4.1.3 on 2023-02-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0005_alter_reservation_reservation_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_day',
            field=models.CharField(max_length=20, verbose_name='予約希望日'),
        ),
    ]
