# Generated by Django 4.1.3 on 2023-02-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0006_alter_reservation_reservation_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_hour',
            field=models.IntegerField(max_length=3, verbose_name='予約時間'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_mail',
            field=models.EmailField(max_length=40, verbose_name='予約者メールアドレス'),
        ),
    ]
