# Generated by Django 4.1.3 on 2023-01-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0006_remove_store_unique_bo_alter_store_holiday1_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('bp_id',), name='unique_bo'),
        ),
    ]
