# Generated by Django 4.1.3 on 2023-02-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0007_alter_reservation_reservation_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_mail',
            field=models.EmailField(blank=True, max_length=40, null=True, verbose_name='予約者メールアドレス'),
        ),
    ]
