"""
Django settings for bazaar project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from local_settings import *
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'top',
    'comp',
    'accounts',
    'bootstrap4',
    'bootstrap_datepicker_plus',
    #'mathfilters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'bazaar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins':[ 
                'bootstrap4.templatetags.bootstrap4',
            ],
            'libraries': {
                'lookup': 'user.lookup' # 追記
            }
        },
    },
]

WSGI_APPLICATION = 'bazaar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

# 画像を保存する先の指定

STATIC_DIR = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATICFILES_DIRS = [
    STATIC_DIR,
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#USER_MODELの指定
AUTH_USER_MODEL = 'accounts.CustomUser'

LOGIN_URL = "accounts:login"

LOGIN_REDIRECT_URL = 'accounts:mypage'
LOGOUT_REDIRECT_URL = "accounts:login"

# アダプターの指定
#ACCOUNT_ADAPTER = 'accounts.adapter.AccountAdapter'
BOOTSTRAP4 = {
    'include_jquery': True,
}

import datetime

PUBLIC_HOLIDAYS = [
    # 2020
    datetime.date(year=2023, month=1, day=1),
    datetime.date(year=2023, month=1, day=13),
    datetime.date(year=2023, month=2, day=11),
    datetime.date(year=2023, month=2, day=23),
    datetime.date(year=2023, month=2, day=24),
    datetime.date(year=2023, month=3, day=20),
    datetime.date(year=2023, month=4, day=29),
    datetime.date(year=2023, month=5, day=3),
    datetime.date(year=2023, month=5, day=4),
    datetime.date(year=2023, month=5, day=5),
    datetime.date(year=2023, month=7, day=20),
    datetime.date(year=2023, month=8, day=11),
    datetime.date(year=2023, month=9, day=21),
    datetime.date(year=2023, month=9, day=22),
    datetime.date(year=2023, month=10, day=12),
    datetime.date(year=2023, month=11, day=3),
    datetime.date(year=2023, month=11, day=23),

    # 2021
    datetime.date(year=2024, month=1, day=1),
    datetime.date(year=2024, month=1, day=11),
    datetime.date(year=2024, month=2, day=11),
    datetime.date(year=2024, month=2, day=23),
    datetime.date(year=2024, month=3, day=20),
    datetime.date(year=2024, month=4, day=29),
    datetime.date(year=2024, month=5, day=3),
    datetime.date(year=2024, month=5, day=4),
    datetime.date(year=2024, month=5, day=5),
    datetime.date(year=2024, month=7, day=19),
    datetime.date(year=2024, month=8, day=11),
    datetime.date(year=2024, month=9, day=20),
    datetime.date(year=2024, month=9, day=23),
    datetime.date(year=2024, month=10, day=11),
    datetime.date(year=2024, month=11, day=3),
    datetime.date(year=2024, month=11, day=23),
]



