from .comp_login_view import CompLoginView
from .comp_logout_view import CompLogoutView
from .comp_signup_view import CompSignupView
from .comp_check_registed_info_view import CompCheckRegistedInfoView
from .comp_send_url_view import CompSendURLView
from .comp_reset_password import CompResetPasswordView
from .comp_update_password_view import CompUpdatePasswordView
from .comp_mypage_views import CompMypageView
from .comp_reservation_list_view import CompReservationListView
from .comp_reservation_detail_view import CompReservationDetailView
from .bo_check_infoviews import CheckRegiInfoView
from .bo_regist_views import CreateAccountView
from .bo_mail_sendviews import BoMailSendView
from .bo_loginviews import BoLoginView
from .bo_mystore_custom_view import CompMyStoreCustomView
from .bo_mystore_info_view import CompStoreInfoView
from .bo_mystore_update_view import CompStoreUpdateView
from .bo_menu_custom_view import CompMenuCustomView
from .bo_custom_select_view import CustomSelectView
from .bo_myaccount_update_view import CompAccountUpdateView