from .user_regist_views import CreateAccountView 
from .user_check_infoviews import CheckRegiInfoView
from .user_complete_registerviews import UserCompleteView
from .user_loginviews import UserLoginView
from .user_mail_sendviews import UserMailSendView
from .user_index_views import UserIndexView
from .user_kutikomi_view import UserKutikomiView
from .user_mypageviews import UserMypageView
from .user_kutikomi_view import KutikomiForm
from .user_check_kutikomiviews import UserCheckKutikomiView
from .user_review_perfectview import UserReviewPerfectView
from .Reservation_list import UserReservationlistView
from .user_info_view import UserInfoView
from .user_accounts_update_view import UserAccountUpdateView
from .user_make_reservation_view import UserMakeReservationView
from .user_select_reservation_view import UserSelectReservationView
from .user_make_reservation_login_view import UserMakeReservationLoginView
from .user_complete_reserve_views import UserCompleteReserveView