# Generated by Django 4.1.3 on 2022-11-25 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8, '8文字以上です'), django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', '英数字のみです！')], verbose_name='ユーザーID')),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, '8文字以上です'), django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', '英数字のみです！')], verbose_name='パスワード')),
                ('rePassword', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, '8文字以上です'), django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', '英数字のみです！')], verbose_name='パスワード')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('mail', models.CharField(max_length=40, verbose_name='メールアドレス')),
                ('phone', models.CharField(max_length=16, verbose_name='電話番号')),
            ],
        ),
    ]
